"""empty message

Revision ID: dd28423509bb
Revises: 
Create Date: 2023-01-18 10:01:08.718586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd28423509bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('walkee_id', sa.Integer(), nullable=True),
    sa.Column('protector_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=1000), nullable=True),
    sa.Column('time', sa.String(length=1000), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('start_location', sa.String(length=1000), nullable=False),
    sa.Column('end_location', sa.String(length=1000), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walkees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walkees')
    op.drop_table('requests')
    op.drop_table('protectors')
    # ### end Alembic commands ###
